apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: super-cool-python-app-1
  description: Test python app, called super-cool-python-app-1
  annotations:
    github.com/project-slug: unicorn-home/super-cool-python-app-1
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: development
  lifecycle: experimental
